name: pcr_marker_design
dependencies:
- bedtools>=2.17
- biopython=1.68=np111py35_0
- cython=0.25.2=py35_0
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.19.1=np111py35_0
- pip=9.0.1=py35_1
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- readline=6.2=2
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - bcbio-gff==0.6.4
  - primer3-py==0.5.1
  - py==1.4.32
  - pybedtools==0.7.8
  - pyfaidx==0.4.8.1
  - pysam==0.9.1.4
  - pytest==3.0.5
  - pyvcf==0.6.8
  - requests==2.12.4
